language: java
deploy:
  provider: releases
  api_key:
    secure: RkAn/oMybQRQAh1WY0Y3kBd4PVAqd81ZyTNA8wVjdtphUhbncK5UQPdzgcJzBO2ED61CZ12i0ZwCU9YbK92pW4eq49LRz1KHVzDE218LGEF9G3r2kX6h2PDFFFiEdzkBKlleb6F67ZTcjSm26nVjN8/asbftDwxcrh8NHrhkCluX4C6jZ+gHvTYxUqHAqNJBDnwIh3ZBnuJ7pFJ2icqGkdOtGY3afsLgNJ3/5rp83txYTG94aqhouKpjuhaKRCId3zgy66kzerlhbBVNUfyvwaIjsWxAox8aiSvxDNSz3zCSZPnEQUK8xktNp9FkoRGLZaB7pxkwBxcpg8+NWkg9i0AZt/JYsluaplJrlxYl7WVH9F+uhxH29KcfyHCbGxHW7dy8aCKAcYhJTazw6/pnkk+sk4u8fs9mdelji3eQz68JenQjLaY1ZlMDwlEksuk1Rru32tlLcKqXI+9HQHcHN65uWs2mBf8lDq8W0+aRERJZBr9iTF8XXHBg3+Z/EsG8/ah2DX0yTAaKoYBZd9CSaMIKBcXhozEVGfbiraeNUm4gZcFsERwvnnHUw2WS2dtWpOxTonEwffCg05L/V4Ta6ioWW1TBzC3KglRqg36bBE6VQKArEIAQgbmJiOx1gtvfSx1MKuNqo277330/bxXmwCnCi8Dy20lgaq0+lyxuZ6E=
  file: target/randomizedEmotes-0.0.2-SNAPSHOT.jar
  skip_cleanup: true
  on:
    repo: Penaz91/randomizedEmotes
  name: 0.0.2 Build $(date + '%d/%m/%Y %R')
